config/routes.rb
JrbhWorklog::Application.routes.draw do
  get "reports/utilization_summary"
  get "reports/individual_summary"
  get "reports/company_summary"
  resources :billing_rates
  resources :roles
  resources :role_allocations
  resources :billing_infos
  resources :timeplans
  resource :user_session
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users
  resources :worklog_tasks
  resources :companies
  resources :work_periods
  match 'dashboard' => 'dashboard#index'
  root :to => 'dashboard#index'
  match '/:controller(/:action(/:id))'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_user

  layout "dashboard"

  def index
    # nothing for us to do, it's all taken care of by filters etc
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%center
  %h2= "Dashboard for user: " + current_user.alias + "(" + current_user.login + ")"
  %h4= link_to 'Logout', logout_path

#worklog
  %p.heading Worklog v4.0
  = link_to 'Edit worklog', :controller => :worklog, :action => :edit
  %br
  = link_to 'Dump data by company', :controller => :csv_generator, :action => :by_company_form
  %br
  = link_to 'Dump data by task', :controller => :csv_generator, :action => :by_task_form

#reports
  %p.heading Reports
  = link_to 'Project(s) report', :controller => :reports, :action => :project_report
  %br
  = link_to 'User report', :controller => :reports, :action => :user_report
  %br
  = link_to 'Company report', :controller => :reports, :action => :company_report

-# Admin panel if we have an admin logged in
-if current_user.admin
  %hr
  %center
    %h3 Administrator Panel
  #users
    %p.heading Users
    = link_to 'Show/Edit/Delete', :controller => :users
    %br
    = link_to 'Add user', :controller => :users, :action => :new
  #companies
    %p.heading Companies
    = link_to 'Show/Edit/Delete', :controller => :companies
    %br
    = link_to 'Add company', :controller => :companies, :action => :new
  #worklog-tasks
    %p.heading Worklog Tasks
    = link_to 'Show/Edit/Delete', :controller => :worklog_tasks
    %br
    = link_to 'Add worklog task', :controller => :worklog_tasks, :action => :new
    %br
    = link_to 'Move periods between tasks', :controller => :move_periods, :action => :index
  #timeplans
    %p.heading Timeplans
    = link_to "Add/Edit/Delete", :controller => :timeplans
  #billinginfos
    %p.heading Billing Info
    = link_to "Add/Edit/Delete", :controller => :billing_infos
  #roles
    %p.heading Roles
    = link_to "Show/Edit/Delete", :controller => :roles
    %br
    = link_to 'Add role', :controller => :roles, :action => :new
  #role_allocations
    %p.heading Role Allocations
    = link_to "Add/Edit/Delete", :controller => :role_allocations
  #billing_rates
    %p.heading Rate Cards
    = link_to "Add/Edit/Delete", :controller => :billing_rates
    %br
    = link_to 'Standard rate card', billing_rates_path(:worklog_task => Hash[:id => WorklogTask.standard_rate_card.id])