config/routes.rb
JrbhWorklog::Application.routes.draw do
  get "reports/utilization_summary"
  get "reports/individual_summary"
  get "reports/company_summary"
  resources :billing_rates
  resources :roles
  resources :role_allocations
  resources :billing_infos
  resources :timeplans
  resource :user_session
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users
  resources :worklog_tasks
  resources :companies
  resources :work_periods
  match 'dashboard' => 'dashboard#index'
  root :to => 'dashboard#index'
  match '/:controller(/:action(/:id))'
end

app/models/worklog_task.rb
class WorklogTask < ActiveRecord::Base
  belongs_to :company
  has_many :work_periods, :dependent => :destroy
  has_many :timeplans
  has_many :billing_infos
  has_many :role_allocations
  
  scope :visible_in_user_menus, where(:visible_in_user_menus => true)
  scope :by_name, order("name")
  
  scope :client_tasks, lambda {
    query = nil
  }
  
  scope :internal_tasks, lambda {
    joins(:company).merge(Company.internal_companies)
  }
  
  scope :internal_tasks_work, lambda {
    joins(:company).where("worklog_tasks.name NOT IN (?)", WorklogTask.internal_non_work_tasks_list).merge(Company.internal_companies)
  }
  
  scope :internal_tasks_non_work, lambda {
    joins(:company).where("worklog_tasks.name IN (?)", WorklogTask.internal_non_work_tasks_list).merge(Company.internal_companies)
  }
  
  scope :external_tasks, lambda {
    joins(:company).merge(Company.external_companies)
  }
  
  scope :holidays, joins(:company).where(:name => "Holiday").merge(Company.jrbh)
  
  scope :sickness, joins(:company).where(:name => "Sickness").merge(Company.jrbh)
  
  default_scope joins(:company).order("companies.name").by_name.readonly(false)
  
  def self.standard_rate_card
    WorklogTask.joins(:company).where("companies.name = ? AND worklog_tasks.name = ?", "JRBH", "Standard Rate Card").first
  end
  
  def self.internal_non_work_tasks_list
    ["Break", "Lunch", "Sickness", "Holiday"]
  end
  
end

app/controllers/worklog_tasks_controller.rb
class WorklogTasksController < ApplicationController
  before_filter :find_worklog_task
  before_filter :require_admin_user

  layout "admin_panel"

  helper_method :available_companies, :available_companies_exists?
          
  WORKLOG_TASKS_PER_PAGE = 20

  def create
    @worklog_task = WorklogTask.new(params[:worklog_task])
    respond_to do |format|
      if @worklog_task.save
        flash[:notice] = 'WorklogTask was successfully created.'
        format.html { redirect_to @worklog_task }
        format.xml  { render :xml => @worklog_task, :status => :created, :location => @worklog_task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @worklog_task.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @worklog_task.destroy
        flash[:notice] = 'WorklogTask was successfully destroyed.'        
        format.html { redirect_to worklog_tasks_path }
        format.xml  { head :ok }
      else
        flash[:error] = 'WorklogTask could not be destroyed.'
        format.html { redirect_to @worklog_task }
        format.xml  { head :unprocessable_entity }
      end
    end
  end

  def index
    @worklog_tasks = WorklogTask.paginate(:page => params[:page], :per_page => WORKLOG_TASKS_PER_PAGE)
    respond_to do |format|
      format.html
      format.xml  { render :xml => @worklog_tasks }
    end
  end

  def edit
  end

  def new
    @worklog_task = WorklogTask.new
    c = Company.first
    @worklog_task.company_id = c.id
    @worklog_task.color = c.color
    respond_to do |format|
      format.html
      format.xml  { render :xml => @worklog_task }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml  { render :xml => @worklog_task }
    end
  end

  def update
    respond_to do |format|
      if @worklog_task.update_attributes(params[:worklog_task])
        flash[:notice] = 'WorklogTask was successfully updated.'
        format.html { redirect_to @worklog_task }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @worklog_task.errors, :status => :unprocessable_entity }
      end
    end
  end

  def company_color
    company_color = Company.find(params[:company_id]).color
    render :partial => 'color_field', :locals => {:company_color => company_color}, :layout => false 
  end

  private

  def available_companies
    Company.order('name ASC').all.map {|c| [ c.name, c.id ] }
  end

  def available_companies_exists?
    !available_companies.blank?
  end

  def find_worklog_task
    @worklog_task = WorklogTask.find(params[:id]) if params[:id]
  end

end

app/helpers/worklog_tasks_helper.rb
module WorklogTasksHelper
end

app/views/worklog_tasks/_color_field.html.haml
= text_field_tag "worklog_task[color]", company_color, :style => "background-color: #{company_color}"
#colorpicker
= farbtastic_create('colorpicker', 'worklog_task_color', true).html_safe

app/views/worklog_tasks/_form.html.haml
//= javascript_include_tag 'edit_worklog_task.js'
:javascript
  $(document).ready(function() {
    $("#worklog_task_company_id").change(function() {
      $.post("#{url_for(:action => 'company_color')}",
        { company_id : $("#worklog_task_company_id").val() },
        function(data) {
          $("#task-color").html(data);
      });
    });
  });

= form_for(worklog_task) do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :company_id
    %br
    = f.select :company_id, available_companies
  %p
    = f.label :color
    %br
    #task-color
      = f.text_field :color
      #colorpicker
      = farbtastic_create('colorpicker', 'worklog_task_color', true).html_safe
  %p
    = f.label :visible_in_user_menus
    %br
    = f.check_box :visible_in_user_menus
  %p
    = f.submit "Submit"

app/views/worklog_tasks/_worklog_task.html.haml
=content_tag_for :div, worklog_task do
  %ul
    %li
      %strong Name:
      =h worklog_task.name
    %li
      %strong Company:
      =h worklog_task.company.name

    %li
      %strong Color:
      = text_field_tag color_id(worklog_task), worklog_task.color, :disabled => true
      = colorpicker_div( :id => colorpicker_id(worklog_task), :class => "colorpicker").html_safe
      = farbtastic_create(colorpicker_id(worklog_task), color_id(worklog_task), false).html_safe

    %li
      %strong Visible in user menus:
      -if worklog_task.visible_in_user_menus
        'Yes'
      -else
        'No'

    = link_to 'Show', worklog_task
    = link_to 'Edit', edit_worklog_task_path(worklog_task)
    = link_to 'Destroy', worklog_task, :confirm => "Are you sure? This worklog task has #{worklog_task.work_periods.size} associated work periods that will also be deleted.", :method => :delete

app/views/worklog_tasks/edit.html.haml
%h2 Editing worklog task
#worklog-tasks
  = render :partial => "form", :locals => {:worklog_task => @worklog_task}

app/views/worklog_tasks/index.html.haml
%h2 Worklog tasks available in the database
#worklog-tasks
  - if !@worklog_tasks.empty?
    = will_paginate(@worklog_tasks)
    .worklog_tasks
      = render :partial => "worklog_task", :collection => @worklog_tasks
    = will_paginate(@worklog_tasks)
  - else
    %p There are no worklog tasks to show yet.

app/views/worklog_tasks/new.html.haml
%h2 Add new worklog task
#worklog-tasks
  - if available_companies_exists?
    = render :partial => "form", :locals => {:worklog_task => @worklog_task}
  - else
    No companies exists so we can't add any worklog tasks yet. Please add companies.
  

app/views/worklog_tasks/show.html.haml
%h2= "Worklog task \"#{@worklog_task.name}\""
#worklog-tasks
  =content_tag_for :div, @worklog_task do
    %ul
      %li
        %strong Name:
        =h @worklog_task.name
      %li
        %strong Company:
        =h @worklog_task.company.name
      %li
        %strong Color:
        = text_field_tag :worklog_task_color, @worklog_task.color, :disabled => true
        #colorpicker
        = farbtastic_create('colorpicker', 'worklog_task_color', false).html_safe
      %li
        %strong Visible in user menus:
        -if @worklog_task.visible_in_user_menus
          'Yes'
        -else
          'No'

  %ul
    %li= link_to 'Edit', edit_worklog_task_path(@worklog_task)
    %li= link_to 'Back', worklog_tasks_path