config/routes.rb
JrbhWorklog::Application.routes.draw do
  get "reports/utilization_summary"
  get "reports/individual_summary"
  get "reports/company_summary"
  resources :billing_rates
  resources :roles
  resources :role_allocations
  resources :billing_infos
  resources :timeplans
  resource :user_session
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users
  resources :worklog_tasks
  resources :companies
  resources :work_periods
  match 'dashboard' => 'dashboard#index'
  root :to => 'dashboard#index'
  match '/:controller(/:action(/:id))'
end

app/models/billing_rate.rb
class BillingRate < ActiveRecord::Base
  belongs_to :worklog_task
  belongs_to :role
  
  scope :for_worklog_task, lambda {|task| where("worklog_task_id = ?", task.id) }
  scope :for_role, lambda {|role| where("role_id = ?", role.id) }

  scope :start_date, lambda {|d|
    where('start_date <= ?', d).order("start_date DESC")
  }
  
  validates_presence_of :start_date, :role_id, :worklog_task_id
  validates_numericality_of :rate, :greather_than => 0
  validate :positive_date_range?
  validate :no_overlapping_periods_for_same_user?

  def positive_date_range?
    if self.start_date > self.adjusted_end_date
      errors.add(:base, "End date must be >= start date!")
    end
  end
  
  def no_overlapping_periods_for_same_user?
    billing_rates = BillingRate.for_role(self.role).for_worklog_task(self.worklog_task).order("start_date")
    billing_rates.each do |billing_rate|
      next if billing_rate.id == self.id
      is_before = self.start_date < billing_rate.start_date and self.adjusted_end_date < billing_rate.start_date
      is_after  = self.start_date > billing_rate.adjusted_end_date and self.adjusted_end_date > billing_rate.adjusted_end_date
      if not (is_before or is_after)
        errors.add(:base, "Role allocation is overlapping with already existing timebilling_rate for user! (start_date: #{billing_rate.start_date}, end_date: #{billing_rate.adjusted_end_date})")
      end
    end
  end
  
  def adjusted_end_date
    ongoing ? Date.today : self.end_date
  end
  
  def ongoing
    self.end_date.nil? 
  end
  
  def ongoing=(flag)
    self.end_date = nil if flag
  end

end

app/controllers/billing_rates_controller.rb
class BillingRatesController < ApplicationController
  before_filter :find_billing_rate
  before_filter :require_admin_user

  layout "admin_panel"

  helper_method :available_roles

  def create
    @billing_rate = BillingRate.new(params[:billing_rate])
    respond_to do |format|
      if @billing_rate.save
        flash[:notice] = 'Rate was successfully created.'
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_rate.worklog_task.id }
        format.xml  { render :xml => @billing_rate, :status => :created, :location => @billing_rate }
      else
        flash[:error] = 'Rate did not validate properly!'
        format.html { render :action => "new" }
        format.xml  { render :xml => @billing_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    worklog_task_id = @billing_rate.worklog_task.id
    respond_to do |format|
      if @billing_rate.destroy
        flash[:notice] = 'Rate was successfully destroyed.'        
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_rate.worklog_task.id }
        format.xml  { head :ok }
      else
        flash[:error] = 'Rate could not be destroyed.'
        format.html { redirect_to @billing_rate }
        format.xml  { head :unprocessable_entity }
      end
    end
  end

  def index
    @companies = Company.order("name").all
    if params[:worklog_task]
      @worklog_task = WorklogTask.find(params[:worklog_task][:id])
      @selected_name = @worklog_task.name
      @billing_rates = BillingRate.for_worklog_task(@worklog_task)
    else
      @worklog_task = nil
      @billing_rates = []
      @selected_name = ""
    end
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_rates }
    end
  end

  def edit
  end

  def new
    raise "No worklog task given!" unless params[:worklog_task_id]
    @billing_rate = BillingRate.new
    @billing_rate.worklog_task = WorklogTask.find(params[:worklog_task_id])
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_rate }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_rate }
    end
  end

  def update
    respond_to do |format|
      if @billing_rate.update_attributes(params[:billing_rate])
        flash[:notice] = 'Rate was successfully updated.'
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_rate.worklog_task.id }
        format.xml  { head :ok }
      else
        flash[:error] = 'Rate did not validate properly!'
        format.html { render :action => "edit" }
        format.xml  { render :xml => @billing_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  private
  
  def available_roles
    Role.order("name ASC").map {|r| [r.name, r.id]}
  end

  def find_billing_rate
    @billing_rate = BillingRate.find(params[:id]) if params[:id]
  end

end

app/helpers/billing_rates_helper.rb
module BillingRatesHelper
end

app/views/billing_rates/_form.html.haml
= form_for(billing_rate) do |f|
  = f.error_messages
  = f.hidden_field :worklog_task_id
  %p
    = f.label :role_id
    %br
    = f.select :role_id, available_roles
  %p
    = f.label :start_date
    %br
    = f.text_field :start_date
  %p
    Ongoing?
    %br
    = f.check_box :ongoing
  %p
    = f.label :end_date
    %br
    = f.text_field :end_date
  %p
    = f.label :rate, "Day rate (GBP)"
    %br
    = f.text_field :rate
  %p
    = f.submit "Submit"

app/views/billing_rates/edit.html.haml
%h3= "Edit billing rate for task '#{@billing_rate.worklog_task.name}' for company '#{@billing_rate.worklog_task.company.name}'"
#billing_rates
  = render :partial => "form", :locals => {:billing_rate => @billing_rate}
  

app/views/billing_rates/index.html.haml
= form_tag(billing_rates_path, :method => :get) do
  = grouped_collection_select(:worklog_task, :id, @companies, :worklog_tasks, :name, :id, :name, :selected => @selected_name, :include_blank => true)
  = submit_tag "Go"
%hr
- unless @worklog_task.nil?
  %h4
    = "Billing rates for task '#{@worklog_task.name}' for company '#{@worklog_task.company.name}'"
  %table
    %thead
      %tr
        %th Start Date
        %th End Date
        %th Role
        %th Day rate (GBP)
        %th Edit
        %th Delete
    %tbody
      - @billing_rates.each do |billing_rate|
        %tr
          %td= billing_rate.start_date
          %td= billing_rate.end_date.nil? ? "Ongoing" : billing_rate.end_date
          %td= billing_rate.role.name
          %td= billing_rate.rate
          %td= link_to "Edit", edit_billing_rate_path(billing_rate)
          %td= link_to "Delete", billing_rate, :method => :delete, :confirm => "Are you sure?"
  = button_to "Add entry", { :action => :new, :worklog_task_id => @worklog_task.id }

app/views/billing_rates/new.html.haml
%h3= "Add new billing rate for task '#{@billing_rate.worklog_task.name}' for company '#{@billing_rate.worklog_task.company.name}'"
#billing_rates
  = render :partial => "form", :locals => {:billing_rate => @billing_rate}
  