config/routes.rb
JrbhWorklog::Application.routes.draw do
  get "reports/utilization_summary"
  get "reports/individual_summary"
  get "reports/company_summary"
  resources :billing_rates
  resources :roles
  resources :role_allocations
  resources :billing_infos
  resources :timeplans
  resource :user_session
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users
  resources :worklog_tasks
  resources :companies
  resources :work_periods
  match 'dashboard' => 'dashboard#index'
  root :to => 'dashboard#index'
  match '/:controller(/:action(/:id))'
end

app/models/billing_info.rb
class BillingInfo < ActiveRecord::Base
  belongs_to :worklog_task
  
  scope :for_worklog_task, lambda {|task| where(:worklog_task => task) }

  scope :overlaps_with, lambda { |start_date, end_date|
    where(
      # contained in period
      {:start_date.gte => start_date, :end_date.lte => end_date} |
      # covers the period
      {:start_date.lte => start_date, :end_date.gte => end_date} |
      # partly covers period, start of it
      {:start_date.lte => start_date, :end_date.gte => start_date, :end_date.lte => end_date} |
      # partly covers period, end of it
      {:start_date.gte => start_date, :start_date.lte => end_date, :end_date.gte => end_date}
    )
  }
  
  validates_presence_of :start_date, :end_date, :worklog_task_id
  validates_numericality_of :invoice_amount
  validate :positive_date_range?
  
  def positive_date_range?
    if self.start_date > self.end_date
      errors.add(:base, "End date must be >= start date!")
    end
  end

end

app/controllers/billing_infos_controller.rb
class BillingInfosController < ApplicationController
  before_filter :find_billing_info
  before_filter :require_admin_user

  layout "admin_panel"

  def create
    @billing_info = BillingInfo.new(params[:billing_info])
    respond_to do |format|
      if @billing_info.save
        flash[:notice] = 'Billing info was successfully created.'
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_info.worklog_task.id }
        format.xml  { render :xml => @billing_info, :status => :created, :location => @billing_info }
      else
        flash[:error] = 'Billing info did not validate properly!'
        format.html { render :action => "new" }
        format.xml  { render :xml => @billing_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    worklog_task_id = @billing_info.worklog_task.id
    respond_to do |format|
      if @billing_info.destroy
        flash[:notice] = 'Billing info was successfully destroyed.'        
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_info.worklog_task.id }
        format.xml  { head :ok }
      else
        flash[:error] = 'Billing info could not be destroyed.'
        format.html { redirect_to @billing_info }
        format.xml  { head :unprocessable_entity }
      end
    end
  end

  def index
    @companies = Company.order("name").all
    if params[:worklog_task]
      @worklog_task = WorklogTask.find(params[:worklog_task][:id])
      @selected_name = @worklog_task.name
      @billing_infos = BillingInfo.for_worklog_task(@worklog_task)
    else
      @worklog_task = nil
      @billing_infos = []
      @selected_name = ""
    end
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_infos }
    end
  end

  def edit
  end

  def new
    raise "No worklog task given!" unless params[:worklog_task_id]
    @billing_info = BillingInfo.new
    @billing_info.worklog_task = WorklogTask.find(params[:worklog_task_id])
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_info }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml  { render :xml => @billing_info }
    end
  end

  def update
    respond_to do |format|
      if @billing_info.update_attributes(params[:billing_info])
        flash[:notice] = 'Billing info was successfully updated.'
        format.html { redirect_to :action => :index, "worklog_task[id]" => @billing_info.worklog_task.id }
        format.xml  { head :ok }
      else
        flash[:error] = 'Billing info did not validate properly!'
        format.html { render :action => "edit" }
        format.xml  { render :xml => @billing_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  private
  
  def find_billing_info
    @billing_info = BillingInfo.find(params[:id]) if params[:id]
  end
  
end

app/helpers/billing_infos_helper.rb
module BillingInfosHelper
end

app/views/billing_infos/_form.html.haml
= form_for(billing_info) do |f|
  = f.error_messages
  = f.hidden_field :worklog_task_id
  %p
    = f.label :start_date
    %br
    = f.text_field :start_date
  %p
    = f.label :end_date
    %br
    = f.text_field :end_date
  %p
    = f.label :invoice_amount
    %br
    = f.text_field :invoice_amount
    GBP
  %p
    = f.submit "Submit"

app/views/billing_infos/edit.html.haml
%h3= "Edit billing info for task '#{@billing_info.worklog_task.name}' for company '#{@billing_info.worklog_task.company.name}'"
#billinginfos
  = render :partial => "form", :locals => {:billing_info => @billing_info}
  

app/views/billing_infos/index.html.haml
= form_tag(billing_infos_path, :method => :get) do
  = grouped_collection_select(:worklog_task, :id, @companies, :worklog_tasks, :name, :id, :name, :selected => @selected_name, :include_blank => true)
  = submit_tag "Go"
%hr
- unless @worklog_task.nil?
  %h4
    = "Billing info for task '#{@worklog_task.name}' for company '#{@worklog_task.company.name}'"
  %table
    %thead
      %tr
        %th Start Date
        %th End Date
        %th Invoice Amount
        %th Edit
        %th Delete
    %tbody
      - @billing_infos.each do |billing|
        %tr
          %td= billing.start_date
          %td= billing.end_date
          %td= billing.invoice_amount
          %td= link_to "Edit", edit_billing_info_path(billing)
          %td= link_to "Delete", billing, :method => :delete, :confirm => "Are you sure?"
  = button_to "Add entry", { :action => :new, :worklog_task_id => @worklog_task.id }
          

app/views/billing_infos/new.html.haml
%h3= "Add new billing info for task '#{@billing_info.worklog_task.name}' for company '#{@billing_info.worklog_task.company.name}'"
#billinginfos
  = render :partial => "form", :locals => {:billing_info => @billing_info}
  